import { Canvas } from '@react-three/fiber';
import { OrbitControls, Grid, Text } from '@react-three/drei';
import { useMemo, useState } from 'react';
import { Bell, Building2, ChevronDown, CircleCheck, Cuboid, Database, Layers, Search, SlidersHorizontal, Sparkles, Map as MapIcon, BarChart3, TableProperties, X, Play, ScanSearch } from 'lucide-react';
import { parcels, buildings, type Building, type Parcel } from './data';

type Selected={type:'parcel';data:Parcel}|{type:'building';data:Building}|{type:'unit';data:Building;floor:number;unit:number}|null;
const layerNames=['Surface Parcels','Buildings','Apartments','Roads','Parking','Underground Utilities','Metro / Elevated Corridors','Terrain','Property Boundaries'];

function City({layers,selected,setSelected,mode,wire,underground}:{layers:Record<string,boolean>;selected:Selected;setSelected:(x:Selected)=>void;mode:'2D'|'3D';wire:boolean;underground:boolean}){
 const is=(t:string,id:string)=>selected?.type===t && selected.data.id===id;
 return <Canvas camera={{position:mode==='2D'?[0,38,0.1]:[28,25,30],fov:45}}><color attach="background" args={['#07111d']}/><ambientLight intensity={1.6}/><directionalLight position={[12,24,8]} intensity={2.8}/>{layers['Terrain']&&<mesh rotation-x={-Math.PI/2} receiveShadow><planeGeometry args={[34,34]}/><meshStandardMaterial color="#132b30" transparent opacity={underground?.36:1}/></mesh>}{layers['Roads']&&<group>{[-7,7].map((p)=><mesh key={p} position={[0,.03,p]}><boxGeometry args={[34,.08,1.3]}/><meshStandardMaterial color="#283a49"/></mesh>)}{[-7,7].map((p)=><mesh key={'v'+p} position={[p,.03,0]}><boxGeometry args={[1.3,.08,34]}/><meshStandardMaterial color="#283a49"/></mesh>)}</group>}
 {layers['Surface Parcels']&&parcels.map(p=><group key={p.id} position={[p.x,.08,p.z]} onClick={(e)=>{e.stopPropagation();setSelected({type:'parcel',data:p})}}><mesh><boxGeometry args={[4.35,.12,4.35]}/><meshStandardMaterial color={is('parcel',p.id)?'#f4b942':p.use==='Residential'?'#164e63':'#1e3a5f'} transparent opacity={.78}/></mesh>{layers['Property Boundaries']&&<mesh position={[0,.08,0]}><boxGeometry args={[4.48,.025,4.48]}/><meshBasicMaterial color="#38bdf8" wireframe/></mesh>}</group>)}
 {layers['Buildings']&&buildings.map(b=><BuildingMesh key={b.id} b={b} selected={selected} onPick={setSelected} wire={wire} apartments={layers['Apartments']}/>) }
 {layers['Metro / Elevated Corridors']&&<group position={[0,5,-1]} onClick={()=>setSelected({type:'building',data:{id:'INF-METRO-01',name:'Elevated Metro Corridor',x:0,z:-1,floors:1,parcel:'ROW-URBAN-02',kind:'Elevated right-of-way'}})}><mesh><boxGeometry args={[32,.5,1]}/><meshStandardMaterial color="#fbbf24" emissive="#6b4d00"/></mesh>{[-12,-4,4,12].map(x=><mesh key={x} position={[x,-3,0]}><boxGeometry args={[.6,6,.6]}/><meshStandardMaterial color="#64748b"/></mesh>)}</group>}
 {(underground&&layers['Underground Utilities'])&&<group position={[0,-2,0]}>{[['#38bdf8',-4],['#f97316',1],['#a78bfa',5]].map(([c,z])=><mesh key={String(z)} position={[0,0,Number(z)]} rotation-z={Math.PI/2}><cylinderGeometry args={[.25,.25,30,16]}/><meshStandardMaterial color={String(c)} emissive={String(c)}/></mesh>)}<Text position={[0,-1,-4]} fontSize={.7} color="#7dd3fc">WATER · -4.2m</Text><Text position={[0,-1,5]} fontSize={.7} color="#c4b5fd">METRO TUNNEL · -18.4m</Text></group>}
 <Grid args={[34,34]} position={[0,.17,0]} cellSize={1} cellThickness={.35} cellColor="#1e6475" sectionSize={5} sectionColor="#247789" fadeDistance={45}/><OrbitControls makeDefault maxPolarAngle={Math.PI/2.05}/></Canvas>;
}
function BuildingMesh({b,selected,onPick,wire,apartments}:{b:Building;selected:Selected;onPick:(s:Selected)=>void;wire:boolean;apartments:boolean}){const picked=selected?.data.id===b.id; const floorPicked=selected?.type==='unit'&&picked?selected.floor:0; return <group position={[b.x,0,b.z]} onClick={(e)=>{e.stopPropagation();onPick({type:'building',data:b})}}>{Array.from({length:b.floors},(_,i)=>{const hot=picked&&(floorPicked===i+1||(!floorPicked&&i===b.floors-1)); return <mesh key={i} position={[0,i*.62+.4,0]} onClick={(e)=>{if(picked&&apartments){e.stopPropagation();onPick({type:'unit',data:b,floor:i+1,unit:1})}}}><boxGeometry args={[3.1,.56,3.1]}/><meshStandardMaterial color={hot?'#f4b942':picked?'#2685b7':'#336f91'} emissive={hot?'#5b3500':'#061c2c'} wireframe={wire}/></mesh>})}</group>}

function App(){const [page,setPage]=useState<'Cadastre'|'Dashboard'|'Properties'|'Analytics'>('Cadastre');const [selected,setSelected]=useState<Selected>(null);const [layers,setLayers]=useState(Object.fromEntries(layerNames.map(x=>[x,true])));const [mode,setMode]=useState<'2D'|'3D'>('3D');const [wire,setWire]=useState(false);const [under,setUnder]=useState(false);const [query,setQuery]=useState('');const [analysis,setAnalysis]=useState(''); const [validated,setValidated]=useState(false);
 const search=useMemo(()=>[...parcels.map(x=>({label:x.id+' · '+x.ul,v:{type:'parcel' as const,data:x}})),...buildings.map(x=>({label:x.id+' · '+x.name,v:{type:'building' as const,data:x}}))].filter(x=>x.label.toLowerCase().includes(query.toLowerCase())).slice(0,5),[query]);
 const choose=(x:Selected)=>{setSelected(x);setPage('Cadastre');setQuery('')};
 return <div className="app"><header><div className="brand"><div className="mark"><Cuboid size={20}/></div><div><b>3D ULPIN</b><span>URBAN LAND & PROPERTY INTELLIGENCE SYSTEM</span></div></div><nav>{['Dashboard','Cadastre','Properties','Analytics'].map(n=><button className={page===n?'active':''} onClick={()=>setPage(n as typeof page)} key={n}>{n==='Cadastre'?'3D Cadastre':n}</button>)}</nav><div className="tools"><button className="city">Amritsar Urban Zone <ChevronDown size={14}/></button><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ULPIN, parcel, building..."/>{query&&<div className="results">{search.map(s=><button key={s.label} onClick={()=>choose(s.v)}>{s.label}</button>)}</div>}</div><Bell size={18}/><div className="avatar">KP</div></div></header>
 {page==='Cadastre'&&<main><aside className="left"><Section icon={<Layers size={15}/>} title="LAYERS">{layerNames.map(n=><label className="toggle" key={n}><input type="checkbox" checked={layers[n]} onChange={e=>setLayers({...layers,[n]:e.target.checked})}/><i/>{n}</label>)}</Section><Section icon={<Database size={15}/>} title="DATA SOURCES"><div className="sources">{['Drone Imagery','LiDAR / Point Cloud','GIS Parcel Data','Floor Plans','GNSS / CORS','DEM / DSM'].map((n,i)=><div key={n}><span>{n}</span><em>{i%2?'Processed':'High Accuracy'}</em></div>)}</div></Section><Section icon={<SlidersHorizontal size={15}/>} title="VISUALIZATION"><div className="seg"><button className={mode==='2D'?'sel':''} onClick={()=>setMode('2D')}>2D</button><button className={mode==='3D'?'sel':''} onClick={()=>setMode('3D')}>3D</button></div><label className="toggle"><input type="checkbox" checked={under} onChange={e=>setUnder(e.target.checked)}/><i/>Underground cutaway</label><label className="toggle"><input type="checkbox" checked={wire} onChange={e=>setWire(e.target.checked)}/><i/>Wireframe mode</label></Section></aside><section className="map"><div className="maphead"><span><MapIcon size={15}/> AMRITSAR URBAN ZONE — DEMONSTRATION AREA</span><span className="live">● LIVE 3D CADASTRE</span></div><City layers={layers} selected={selected} setSelected={setSelected} mode={mode} wire={wire} underground={under}/><div className="maphint">Drag to orbit · Scroll to zoom · Click parcels, structures & floor volumes</div></section><aside className="right"><PropertyPanel selected={selected} choose={choose}/><div className="actions"><button onClick={()=>{setAnalysis('processing');setTimeout(()=>setAnalysis('done'),1200)}}><Sparkles size={16}/>{analysis==='processing'?'Extracting 3D features…':'Run AI Analysis'}</button><button onClick={()=>setValidated(true)}><ScanSearch size={16}/>Validate Topology</button></div>{analysis==='done'&&<Notice title="AI-ASSISTED EXTRACTION" lines={['Building Extraction  98.4%','Floor Segmentation  96.8%','Parcel Boundaries  97.2%','Analysis Complete']}/>} {validated&&<Notice title="TOPOLOGY VALIDATION" lines={['No overlapping parcels','Building inside boundary','Floor volumes aligned','Vertical boundaries valid']}/>}</aside></main>}
 {page==='Dashboard'&&<Dashboard go={()=>setPage('Cadastre')}/>} {page==='Analytics'&&<Analytics/>} {page==='Properties'&&<Registry choose={choose}/>}<footer><span>EPSG:4326 · CORS Reference: AMR-01 · Accuracy ±2.4cm</span><span>25 PARCELS · 12 BUILDINGS · 86 VERTICAL UNITS · 7 UNDERGROUND ASSETS</span><span className="legend">■ Parcel　■ Building　■ Selected　■ Utility</span></footer></div>}
function Section(p:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="section"><h3>{p.icon}{p.title}</h3>{p.children}</section>}
function Notice({title,lines}:{title:string;lines:string[]}){return <div className="notice"><b><CircleCheck size={15}/>{title}</b>{lines.map(x=><span key={x}>✓ {x}</span>)}</div>}
function PropertyPanel({selected,choose}:{selected:Selected;choose:(s:Selected)=>void}){if(!selected)return <div className="overview"><h2>Urban Property Overview</h2><p>Integrated 3D cadastral intelligence</p>{[['Total Parcels','12,842'],['3D Mapped Buildings','8,421'],['Registered Units','36,920'],['Underground Assets','2,184'],['3D Property Volumes','58,746']].map(x=><div className="stat" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>;if(selected.type==='parcel'){const p=selected.data;let b=buildings.find(x=>x.parcel===p.id);return <div className="details"><label>PROPERTY DETAILS</label><h2>{p.id}</h2><code>{p.ul}</code><dl><dt>Area</dt><dd>{p.area} m²</dd><dt>Land Use</dt><dd>{p.use}</dd><dt>Ownership</dt><dd>Registered / Freehold</dd><dt>Coordinates</dt><dd>31.634° N, 74.872° E</dd></dl>{b&&<button className="primary" onClick={()=>choose({type:'building',data:b})}>View building in 3D</button>}</div>}const b=selected.data; if(selected.type==='unit')return <div className="details"><label>VERTICAL PROPERTY</label><h2>{b.name}</h2><code>ULPIN-03-PB-AMR-004828-{String(selected.floor).padStart(2,'0')}-{String(selected.unit).padStart(2,'0')}</code><div className="volume">F{selected.floor}<span>UNIT A-{selected.floor}0{selected.unit}</span></div><dl><dt>Apartment</dt><dd>A-{selected.floor}0{selected.unit}</dd><dt>Area</dt><dd>93 m²</dd><dt>Elevation</dt><dd>{(selected.floor*.62).toFixed(1)} m</dd><dt>Usage</dt><dd>Residential</dd><dt>Vertical extent</dt><dd>2.9 m</dd></dl></div>;return <div className="details"><label>BUILDING DETAILS</label><h2>{b.name}</h2><code>{b.id} · {b.parcel}</code><dl><dt>Height</dt><dd>{(b.floors*3.1).toFixed(1)} m</dd><dt>Floors</dt><dd>{b.floors}</dd><dt>Construction</dt><dd>{b.kind}</dd><dt>Built-up Area</dt><dd>{b.floors*290} m²</dd></dl><h4>FLOOR REGISTER</h4><div className="floors">{Array.from({length:b.floors},(_,i)=><button key={i} onClick={()=>choose({type:'unit',data:b,floor:b.floors-i,unit:1})}>F{b.floors-i}<span>4 units</span></button>)}</div></div>}
function Dashboard({go}:{go:()=>void}){return <div className="page"><div className="title"><span>National Urban 3D Cadastral Command Center</span><h1>Amritsar Demonstration Area</h1></div><div className="cards">{[['Land Parcels','12,842'],['3D Mapped Buildings','8,421'],['Vertical Properties','36,920'],['Underground Assets','2,184'],['3D Coverage','87.6%'],['Survey Accuracy','96.8%']].map(x=><div><span>{x[0]}</span><b>{x[1]}</b><em>↑ verified this cycle</em></div>)}</div><div className="dashgrid"><div className="chart"><h3>3D cadastral coverage</h3><div className="bars">{[48,65,57,79,71,88,82,95].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div></div><div className="chart"><h3>Demo journey</h3><p>Explore the full vertical property registry, underground assets and elevated right-of-way in a responsive WebGL cadastre.</p><button className="primary" onClick={go}><Play size={15}/> Launch 3D Cadastre</button></div></div></div>}
function Analytics(){return <div className="page"><div className="title"><span>National 3D mapping programme</span><h1>Urban Cadastre Analytics</h1></div><div className="cards">{[['Mapped Coverage','87.6%'],['Topology pass rate','99.2%'],['Floor plans indexed','32,148'],['Assets digitized','2,184']].map(x=><div><span>{x[0]}</span><b>{x[1]}</b><em>Amritsar zone</em></div>)}</div><div className="dashgrid"><div className="chart"><h3>Buildings by height</h3><div className="bars">{[24,45,84,62,72,39,92,57].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div></div><div className="chart"><h3>Land use distribution</h3><div className="pie">Residential 48%<br/>Commercial 22%<br/>Mixed use 18%<br/>Public 12%</div></div></div></div>}
function Registry({choose}:{choose:(x:Selected)=>void}){return <div className="page registry"><div className="title"><span>Searchable vertical registry</span><h1>Property Records</h1></div><table><thead><tr>{['3D ULPIN','Parcel ID','Building','Floor','Unit','Area','Property Type','Status'].map(x=><th>{x}</th>)}</tr></thead><tbody>{buildings.flatMap(b=>[1,2,3,4].map((u,i)=><tr onClick={()=>choose({type:'unit',data:b,floor:Math.min(8,b.floors),unit:u})}><td>ULPIN-03-PB-AMR-00482{i}-{u}</td><td>{b.parcel}</td><td>{b.name}</td><td>{Math.min(8,b.floors)}</td><td>A-80{u}</td><td>{82+u*4}m²</td><td>Apartment</td><td><em>Registered</em></td></tr>))}</tbody></table></div>}
export default App;
